#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 133
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 75
#define ALIAS_COUNT 0
#define TOKEN_COUNT 41
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 2

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_i32 = 2,
  anon_sym_u32 = 3,
  anon_sym_i64 = 4,
  anon_sym_u64 = 5,
  anon_sym_f32 = 6,
  anon_sym_f64 = 7,
  anon_sym_bool = 8,
  anon_sym_char = 9,
  anon_sym_str = 10,
  anon_sym_usize = 11,
  anon_sym_STAR = 12,
  anon_sym_const = 13,
  anon_sym_mut = 14,
  anon_sym_LPAREN = 15,
  anon_sym_RPAREN = 16,
  anon_sym_LBRACK = 17,
  anon_sym_SEMI = 18,
  anon_sym_RBRACK = 19,
  anon_sym_COMMA = 20,
  anon_sym_COLON = 21,
  anon_sym_let = 22,
  anon_sym_fn = 23,
  anon_sym_DASH_GT = 24,
  anon_sym_LBRACE = 25,
  anon_sym_RBRACE = 26,
  anon_sym_EQ = 27,
  anon_sym_BANG = 28,
  anon_sym_DASH = 29,
  anon_sym_DOT = 30,
  anon_sym_copy = 31,
  sym_int = 32,
  sym_uint = 33,
  sym_float = 34,
  anon_sym_true = 35,
  anon_sym_false = 36,
  sym_bytes = 37,
  sym_static_string = 38,
  sym_line_comment = 39,
  sym_block_comment = 40,
  sym_program = 41,
  sym__toplevel_statement = 42,
  sym_type = 43,
  sym_primitive_type = 44,
  sym_pointer_type = 45,
  sym_array_type = 46,
  sym_tuple_type = 47,
  sym_parameters = 48,
  sym_parameter = 49,
  sym_returns = 50,
  sym_declaration = 51,
  sym_variable_declaration = 52,
  sym_function_declaration = 53,
  sym_function_header = 54,
  sym_function_body = 55,
  sym_statement = 56,
  sym_assignment_statement = 57,
  sym_expression = 58,
  sym_binary_expression = 59,
  sym_unary_expression = 60,
  sym_function_call_expression = 61,
  sym__lvalue = 62,
  sym_field_access = 63,
  sym_array_access = 64,
  sym_const_expression = 65,
  sym_copy_expression = 66,
  sym_constant = 67,
  sym_bool = 68,
  aux_sym_program_repeat1 = 69,
  aux_sym_tuple_type_repeat1 = 70,
  aux_sym_parameters_repeat1 = 71,
  aux_sym_returns_repeat1 = 72,
  aux_sym_function_body_repeat1 = 73,
  aux_sym_function_call_expression_repeat1 = 74,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_i32] = "i32",
  [anon_sym_u32] = "u32",
  [anon_sym_i64] = "i64",
  [anon_sym_u64] = "u64",
  [anon_sym_f32] = "f32",
  [anon_sym_f64] = "f64",
  [anon_sym_bool] = "bool",
  [anon_sym_char] = "char",
  [anon_sym_str] = "str",
  [anon_sym_usize] = "usize",
  [anon_sym_STAR] = "*",
  [anon_sym_const] = "const",
  [anon_sym_mut] = "mut",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_SEMI] = ";",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [anon_sym_let] = "let",
  [anon_sym_fn] = "fn",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG] = "!",
  [anon_sym_DASH] = "-",
  [anon_sym_DOT] = ".",
  [anon_sym_copy] = "copy",
  [sym_int] = "int",
  [sym_uint] = "uint",
  [sym_float] = "float",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_bytes] = "bytes",
  [sym_static_string] = "static_string",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_program] = "program",
  [sym__toplevel_statement] = "_toplevel_statement",
  [sym_type] = "type",
  [sym_primitive_type] = "primitive_type",
  [sym_pointer_type] = "pointer_type",
  [sym_array_type] = "array_type",
  [sym_tuple_type] = "tuple_type",
  [sym_parameters] = "parameters",
  [sym_parameter] = "parameter",
  [sym_returns] = "returns",
  [sym_declaration] = "declaration",
  [sym_variable_declaration] = "variable_declaration",
  [sym_function_declaration] = "function_declaration",
  [sym_function_header] = "function_header",
  [sym_function_body] = "function_body",
  [sym_statement] = "statement",
  [sym_assignment_statement] = "assignment_statement",
  [sym_expression] = "expression",
  [sym_binary_expression] = "binary_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_function_call_expression] = "function_call_expression",
  [sym__lvalue] = "_lvalue",
  [sym_field_access] = "field_access",
  [sym_array_access] = "array_access",
  [sym_const_expression] = "const_expression",
  [sym_copy_expression] = "copy_expression",
  [sym_constant] = "constant",
  [sym_bool] = "bool",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_tuple_type_repeat1] = "tuple_type_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_returns_repeat1] = "returns_repeat1",
  [aux_sym_function_body_repeat1] = "function_body_repeat1",
  [aux_sym_function_call_expression_repeat1] = "function_call_expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_u32] = anon_sym_u32,
  [anon_sym_i64] = anon_sym_i64,
  [anon_sym_u64] = anon_sym_u64,
  [anon_sym_f32] = anon_sym_f32,
  [anon_sym_f64] = anon_sym_f64,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_char] = anon_sym_char,
  [anon_sym_str] = anon_sym_str,
  [anon_sym_usize] = anon_sym_usize,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_mut] = anon_sym_mut,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_copy] = anon_sym_copy,
  [sym_int] = sym_int,
  [sym_uint] = sym_uint,
  [sym_float] = sym_float,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_bytes] = sym_bytes,
  [sym_static_string] = sym_static_string,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_program] = sym_program,
  [sym__toplevel_statement] = sym__toplevel_statement,
  [sym_type] = sym_type,
  [sym_primitive_type] = sym_primitive_type,
  [sym_pointer_type] = sym_pointer_type,
  [sym_array_type] = sym_array_type,
  [sym_tuple_type] = sym_tuple_type,
  [sym_parameters] = sym_parameters,
  [sym_parameter] = sym_parameter,
  [sym_returns] = sym_returns,
  [sym_declaration] = sym_declaration,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_function_declaration] = sym_function_declaration,
  [sym_function_header] = sym_function_header,
  [sym_function_body] = sym_function_body,
  [sym_statement] = sym_statement,
  [sym_assignment_statement] = sym_assignment_statement,
  [sym_expression] = sym_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_function_call_expression] = sym_function_call_expression,
  [sym__lvalue] = sym__lvalue,
  [sym_field_access] = sym_field_access,
  [sym_array_access] = sym_array_access,
  [sym_const_expression] = sym_const_expression,
  [sym_copy_expression] = sym_copy_expression,
  [sym_constant] = sym_constant,
  [sym_bool] = sym_bool,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_tuple_type_repeat1] = aux_sym_tuple_type_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_returns_repeat1] = aux_sym_returns_repeat1,
  [aux_sym_function_body_repeat1] = aux_sym_function_body_repeat1,
  [aux_sym_function_call_expression_repeat1] = aux_sym_function_call_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_char] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_usize] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mut] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_copy] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_uint] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_bytes] = {
    .visible = true,
    .named = true,
  },
  [sym_static_string] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__toplevel_statement] = {
    .visible = false,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_pointer_type] = {
    .visible = true,
    .named = true,
  },
  [sym_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_type] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_returns] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_header] = {
    .visible = true,
    .named = true,
  },
  [sym_function_body] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__lvalue] = {
    .visible = false,
    .named = true,
  },
  [sym_field_access] = {
    .visible = true,
    .named = true,
  },
  [sym_array_access] = {
    .visible = true,
    .named = true,
  },
  [sym_const_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_copy_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tuple_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_returns_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_left = 1,
  field_right = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 0},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 3,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 13,
  [17] = 12,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 20,
  [24] = 21,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 31,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 37,
  [53] = 53,
  [54] = 44,
  [55] = 53,
  [56] = 45,
  [57] = 33,
  [58] = 35,
  [59] = 38,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 60,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 80,
  [85] = 85,
  [86] = 79,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 81,
  [91] = 91,
  [92] = 82,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 95,
  [119] = 98,
  [120] = 110,
  [121] = 107,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 97,
  [128] = 125,
  [129] = 116,
  [130] = 130,
  [131] = 113,
  [132] = 132,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '!', 23,
        '"', 2,
        '(', 12,
        ')', 13,
        '*', 11,
        ',', 17,
        '-', 25,
        '.', 26,
        '/', 4,
        ':', 18,
        ';', 15,
        '=', 22,
        '[', 14,
        ']', 16,
        'b', 27,
        '{', 20,
        '}', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(23);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'b') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(34);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(19);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(19);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '"') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == 'u') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_uint);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_bytes);
      if (lookahead == '"') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_static_string);
      if (lookahead == '"') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'b', 1,
        'c', 2,
        'f', 3,
        'i', 4,
        'l', 5,
        'm', 6,
        's', 7,
        't', 8,
        'u', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == 'h') ADVANCE(11);
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == '3') ADVANCE(13);
      if (lookahead == '6') ADVANCE(14);
      if (lookahead == 'a') ADVANCE(15);
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == '3') ADVANCE(17);
      if (lookahead == '6') ADVANCE(18);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == '3') ADVANCE(23);
      if (lookahead == '6') ADVANCE(24);
      if (lookahead == 's') ADVANCE(25);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(28);
      if (lookahead == 'p') ADVANCE(29);
      END_STATE();
    case 13:
      if (lookahead == '2') ADVANCE(30);
      END_STATE();
    case 14:
      if (lookahead == '4') ADVANCE(31);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 17:
      if (lookahead == '2') ADVANCE(33);
      END_STATE();
    case 18:
      if (lookahead == '4') ADVANCE(34);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(38);
      END_STATE();
    case 23:
      if (lookahead == '2') ADVANCE(39);
      END_STATE();
    case 24:
      if (lookahead == '4') ADVANCE(40);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(41);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 29:
      if (lookahead == 'y') ADVANCE(45);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_f32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_f64);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(46);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_i32);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_i64);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_mut);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_str);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_u32);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_u64);
      END_STATE();
    case 41:
      if (lookahead == 'z') ADVANCE(48);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_char);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_copy);
      END_STATE();
    case 46:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_usize);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 7},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 7},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_u32] = ACTIONS(1),
    [anon_sym_i64] = ACTIONS(1),
    [anon_sym_u64] = ACTIONS(1),
    [anon_sym_f32] = ACTIONS(1),
    [anon_sym_f64] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_char] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [anon_sym_usize] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_mut] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_copy] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [sym_uint] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_bytes] = ACTIONS(1),
    [sym_static_string] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_program] = STATE(102),
    [sym__toplevel_statement] = STATE(18),
    [sym_declaration] = STATE(18),
    [sym_variable_declaration] = STATE(37),
    [sym_function_declaration] = STATE(37),
    [sym_function_header] = STATE(81),
    [sym_statement] = STATE(18),
    [sym_assignment_statement] = STATE(55),
    [sym__lvalue] = STATE(97),
    [sym_field_access] = STATE(97),
    [sym_array_access] = STATE(97),
    [aux_sym_program_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_fn] = ACTIONS(11),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_RPAREN,
    ACTIONS(19), 1,
      anon_sym_copy,
    ACTIONS(21), 1,
      sym_int,
    STATE(36), 1,
      sym_constant,
    STATE(65), 1,
      sym_bool,
    STATE(68), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 4,
      sym_uint,
      sym_float,
      sym_bytes,
      sym_static_string,
    STATE(34), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call_expression,
      sym__lvalue,
      sym_field_access,
      sym_array_access,
      sym_const_expression,
      sym_copy_expression,
  [50] = 11,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_copy,
    ACTIONS(21), 1,
      sym_int,
    STATE(36), 1,
      sym_constant,
    STATE(65), 1,
      sym_bool,
    STATE(95), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 4,
      sym_uint,
      sym_float,
      sym_bytes,
      sym_static_string,
    STATE(34), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call_expression,
      sym__lvalue,
      sym_field_access,
      sym_array_access,
      sym_const_expression,
      sym_copy_expression,
  [97] = 11,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_copy,
    ACTIONS(21), 1,
      sym_int,
    STATE(36), 1,
      sym_constant,
    STATE(63), 1,
      sym_expression,
    STATE(65), 1,
      sym_bool,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 4,
      sym_uint,
      sym_float,
      sym_bytes,
      sym_static_string,
    STATE(34), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call_expression,
      sym__lvalue,
      sym_field_access,
      sym_array_access,
      sym_const_expression,
      sym_copy_expression,
  [144] = 11,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_copy,
    ACTIONS(21), 1,
      sym_int,
    STATE(36), 1,
      sym_constant,
    STATE(65), 1,
      sym_bool,
    STATE(111), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 4,
      sym_uint,
      sym_float,
      sym_bytes,
      sym_static_string,
    STATE(34), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call_expression,
      sym__lvalue,
      sym_field_access,
      sym_array_access,
      sym_const_expression,
      sym_copy_expression,
  [191] = 11,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_copy,
    ACTIONS(21), 1,
      sym_int,
    STATE(36), 1,
      sym_constant,
    STATE(62), 1,
      sym_expression,
    STATE(65), 1,
      sym_bool,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 4,
      sym_uint,
      sym_float,
      sym_bytes,
      sym_static_string,
    STATE(34), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call_expression,
      sym__lvalue,
      sym_field_access,
      sym_array_access,
      sym_const_expression,
      sym_copy_expression,
  [238] = 11,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_copy,
    ACTIONS(21), 1,
      sym_int,
    STATE(36), 1,
      sym_constant,
    STATE(65), 1,
      sym_bool,
    STATE(118), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 4,
      sym_uint,
      sym_float,
      sym_bytes,
      sym_static_string,
    STATE(34), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call_expression,
      sym__lvalue,
      sym_field_access,
      sym_array_access,
      sym_const_expression,
      sym_copy_expression,
  [285] = 11,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_copy,
    ACTIONS(21), 1,
      sym_int,
    STATE(36), 1,
      sym_constant,
    STATE(65), 1,
      sym_bool,
    STATE(87), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 4,
      sym_uint,
      sym_float,
      sym_bytes,
      sym_static_string,
    STATE(34), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_function_call_expression,
      sym__lvalue,
      sym_field_access,
      sym_array_access,
      sym_const_expression,
      sym_copy_expression,
  [332] = 9,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_RPAREN,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    STATE(67), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(61), 4,
      sym_primitive_type,
      sym_pointer_type,
      sym_array_type,
      sym_tuple_type,
    ACTIONS(29), 10,
      anon_sym_i32,
      anon_sym_u32,
      anon_sym_i64,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_str,
      anon_sym_usize,
  [373] = 8,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    STATE(117), 1,
      sym_type,
    STATE(122), 1,
      sym_returns,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(61), 4,
      sym_primitive_type,
      sym_pointer_type,
      sym_array_type,
      sym_tuple_type,
    ACTIONS(39), 10,
      anon_sym_i32,
      anon_sym_u32,
      anon_sym_i64,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_str,
      anon_sym_usize,
  [411] = 8,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    STATE(117), 1,
      sym_type,
    STATE(130), 1,
      sym_returns,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(61), 4,
      sym_primitive_type,
      sym_pointer_type,
      sym_array_type,
      sym_tuple_type,
    ACTIONS(39), 10,
      anon_sym_i32,
      anon_sym_u32,
      anon_sym_i64,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_str,
      anon_sym_usize,
  [449] = 7,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    STATE(110), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(61), 4,
      sym_primitive_type,
      sym_pointer_type,
      sym_array_type,
      sym_tuple_type,
    ACTIONS(39), 10,
      anon_sym_i32,
      anon_sym_u32,
      anon_sym_i64,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_str,
      anon_sym_usize,
  [484] = 7,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    STATE(98), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(61), 4,
      sym_primitive_type,
      sym_pointer_type,
      sym_array_type,
      sym_tuple_type,
    ACTIONS(39), 10,
      anon_sym_i32,
      anon_sym_u32,
      anon_sym_i64,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_str,
      anon_sym_usize,
  [519] = 7,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    STATE(89), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(61), 4,
      sym_primitive_type,
      sym_pointer_type,
      sym_array_type,
      sym_tuple_type,
    ACTIONS(39), 10,
      anon_sym_i32,
      anon_sym_u32,
      anon_sym_i64,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_str,
      anon_sym_usize,
  [554] = 7,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    STATE(91), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(61), 4,
      sym_primitive_type,
      sym_pointer_type,
      sym_array_type,
      sym_tuple_type,
    ACTIONS(39), 10,
      anon_sym_i32,
      anon_sym_u32,
      anon_sym_i64,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_str,
      anon_sym_usize,
  [589] = 7,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    STATE(119), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(61), 4,
      sym_primitive_type,
      sym_pointer_type,
      sym_array_type,
      sym_tuple_type,
    ACTIONS(39), 10,
      anon_sym_i32,
      anon_sym_u32,
      anon_sym_i64,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_str,
      anon_sym_usize,
  [624] = 7,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    STATE(120), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(61), 4,
      sym_primitive_type,
      sym_pointer_type,
      sym_array_type,
      sym_tuple_type,
    ACTIONS(39), 10,
      anon_sym_i32,
      anon_sym_u32,
      anon_sym_i64,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_str,
      anon_sym_usize,
  [659] = 10,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    STATE(55), 1,
      sym_assignment_statement,
    STATE(81), 1,
      sym_function_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(37), 2,
      sym_variable_declaration,
      sym_function_declaration,
    STATE(97), 3,
      sym__lvalue,
      sym_field_access,
      sym_array_access,
    STATE(19), 4,
      sym__toplevel_statement,
      sym_declaration,
      sym_statement,
      aux_sym_program_repeat1,
  [697] = 10,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 1,
      sym_identifier,
    ACTIONS(58), 1,
      anon_sym_let,
    ACTIONS(61), 1,
      anon_sym_fn,
    STATE(55), 1,
      sym_assignment_statement,
    STATE(81), 1,
      sym_function_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(37), 2,
      sym_variable_declaration,
      sym_function_declaration,
    STATE(97), 3,
      sym__lvalue,
      sym_field_access,
      sym_array_access,
    STATE(19), 4,
      sym__toplevel_statement,
      sym_declaration,
      sym_statement,
      aux_sym_program_repeat1,
  [735] = 10,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(64), 1,
      anon_sym_let,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    STATE(53), 1,
      sym_assignment_statement,
    STATE(90), 1,
      sym_function_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(52), 2,
      sym_variable_declaration,
      sym_function_declaration,
    STATE(21), 3,
      sym_declaration,
      sym_statement,
      aux_sym_function_body_repeat1,
    STATE(127), 3,
      sym__lvalue,
      sym_field_access,
      sym_array_access,
  [772] = 10,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(64), 1,
      anon_sym_let,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    STATE(53), 1,
      sym_assignment_statement,
    STATE(90), 1,
      sym_function_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(52), 2,
      sym_variable_declaration,
      sym_function_declaration,
    STATE(22), 3,
      sym_declaration,
      sym_statement,
      aux_sym_function_body_repeat1,
    STATE(127), 3,
      sym__lvalue,
      sym_field_access,
      sym_array_access,
  [809] = 10,
    ACTIONS(70), 1,
      sym_identifier,
    ACTIONS(73), 1,
      anon_sym_let,
    ACTIONS(76), 1,
      anon_sym_fn,
    ACTIONS(79), 1,
      anon_sym_RBRACE,
    STATE(53), 1,
      sym_assignment_statement,
    STATE(90), 1,
      sym_function_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(52), 2,
      sym_variable_declaration,
      sym_function_declaration,
    STATE(22), 3,
      sym_declaration,
      sym_statement,
      aux_sym_function_body_repeat1,
    STATE(127), 3,
      sym__lvalue,
      sym_field_access,
      sym_array_access,
  [846] = 10,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(64), 1,
      anon_sym_let,
    ACTIONS(81), 1,
      anon_sym_RBRACE,
    STATE(53), 1,
      sym_assignment_statement,
    STATE(90), 1,
      sym_function_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(52), 2,
      sym_variable_declaration,
      sym_function_declaration,
    STATE(24), 3,
      sym_declaration,
      sym_statement,
      aux_sym_function_body_repeat1,
    STATE(127), 3,
      sym__lvalue,
      sym_field_access,
      sym_array_access,
  [883] = 10,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(64), 1,
      anon_sym_let,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    STATE(53), 1,
      sym_assignment_statement,
    STATE(90), 1,
      sym_function_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(52), 2,
      sym_variable_declaration,
      sym_function_declaration,
    STATE(22), 3,
      sym_declaration,
      sym_statement,
      aux_sym_function_body_repeat1,
    STATE(127), 3,
      sym__lvalue,
      sym_field_access,
      sym_array_access,
  [920] = 4,
    ACTIONS(85), 1,
      anon_sym_LPAREN,
    STATE(39), 1,
      sym_primitive_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(39), 10,
      anon_sym_i32,
      anon_sym_u32,
      anon_sym_i64,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_str,
      anon_sym_usize,
  [943] = 3,
    STATE(126), 1,
      sym_primitive_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(39), 10,
      anon_sym_i32,
      anon_sym_u32,
      anon_sym_i64,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_str,
      anon_sym_usize,
  [963] = 5,
    ACTIONS(87), 1,
      anon_sym_LPAREN,
    ACTIONS(91), 1,
      anon_sym_LBRACK,
    ACTIONS(93), 1,
      anon_sym_DOT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(89), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [983] = 4,
    ACTIONS(91), 1,
      anon_sym_LBRACK,
    ACTIONS(93), 1,
      anon_sym_DOT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(89), 5,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_EQ,
  [1001] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(95), 5,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_EQ,
  [1013] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(97), 5,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_EQ,
  [1025] = 3,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(99), 3,
      anon_sym_let,
      anon_sym_fn,
      sym_identifier,
  [1038] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(103), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [1049] = 3,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(107), 3,
      anon_sym_let,
      anon_sym_fn,
      sym_identifier,
  [1062] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(109), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [1073] = 3,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(113), 3,
      anon_sym_let,
      anon_sym_fn,
      sym_identifier,
  [1086] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(115), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [1097] = 3,
    ACTIONS(117), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(119), 3,
      anon_sym_let,
      anon_sym_fn,
      sym_identifier,
  [1110] = 3,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(123), 3,
      anon_sym_let,
      anon_sym_fn,
      sym_identifier,
  [1123] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(125), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
  [1134] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
  [1145] = 3,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(99), 3,
      anon_sym_let,
      anon_sym_fn,
      sym_identifier,
  [1158] = 5,
    ACTIONS(129), 1,
      sym_identifier,
    ACTIONS(131), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      sym_parameter,
    STATE(132), 1,
      sym_parameters,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1175] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(133), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [1186] = 3,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(137), 3,
      anon_sym_let,
      anon_sym_fn,
      sym_identifier,
  [1199] = 3,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(141), 3,
      anon_sym_let,
      anon_sym_fn,
      sym_identifier,
  [1212] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(143), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
  [1223] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(145), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
  [1234] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(147), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [1245] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(149), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
  [1256] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(151), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
  [1267] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(153), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [1278] = 3,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(119), 3,
      anon_sym_let,
      anon_sym_fn,
      sym_identifier,
  [1291] = 3,
    ACTIONS(157), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(155), 3,
      anon_sym_let,
      anon_sym_fn,
      sym_identifier,
  [1304] = 3,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(137), 3,
      anon_sym_let,
      anon_sym_fn,
      sym_identifier,
  [1317] = 3,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(155), 3,
      anon_sym_let,
      anon_sym_fn,
      sym_identifier,
  [1330] = 3,
    ACTIONS(139), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(141), 3,
      anon_sym_let,
      anon_sym_fn,
      sym_identifier,
  [1343] = 3,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(107), 3,
      anon_sym_let,
      anon_sym_fn,
      sym_identifier,
  [1356] = 3,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(113), 3,
      anon_sym_let,
      anon_sym_fn,
      sym_identifier,
  [1369] = 3,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(123), 3,
      anon_sym_let,
      anon_sym_fn,
      sym_identifier,
  [1382] = 3,
    ACTIONS(161), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(159), 3,
      anon_sym_let,
      anon_sym_fn,
      sym_identifier,
  [1395] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(163), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
  [1406] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(165), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [1417] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(167), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [1428] = 3,
    ACTIONS(169), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(29), 3,
      sym__lvalue,
      sym_field_access,
      sym_array_access,
  [1441] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(171), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [1452] = 3,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(159), 3,
      anon_sym_let,
      anon_sym_fn,
      sym_identifier,
  [1465] = 4,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
    ACTIONS(175), 1,
      anon_sym_COMMA,
    STATE(72), 1,
      aux_sym_returns_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1479] = 4,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    ACTIONS(179), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      aux_sym_function_call_expression_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1493] = 4,
    ACTIONS(181), 1,
      anon_sym_RPAREN,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    STATE(69), 1,
      aux_sym_function_call_expression_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1507] = 4,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym_tuple_type_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1521] = 4,
    ACTIONS(179), 1,
      anon_sym_COMMA,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      aux_sym_function_call_expression_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1535] = 4,
    ACTIONS(175), 1,
      anon_sym_COMMA,
    ACTIONS(192), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      aux_sym_returns_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1549] = 4,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    ACTIONS(194), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      aux_sym_tuple_type_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1563] = 4,
    ACTIONS(196), 1,
      anon_sym_RPAREN,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_parameters_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1577] = 4,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    STATE(75), 1,
      aux_sym_returns_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1591] = 4,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      aux_sym_parameters_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1605] = 4,
    ACTIONS(207), 1,
      anon_sym_RPAREN,
    ACTIONS(209), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym_parameters_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1619] = 4,
    ACTIONS(212), 1,
      anon_sym_RPAREN,
    ACTIONS(214), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym_tuple_type_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1633] = 3,
    ACTIONS(217), 1,
      sym_identifier,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1644] = 3,
    ACTIONS(221), 1,
      sym_identifier,
    ACTIONS(223), 1,
      anon_sym_mut,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1655] = 3,
    ACTIONS(225), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_function_body,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1666] = 3,
    ACTIONS(217), 1,
      sym_identifier,
    ACTIONS(227), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1677] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(212), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1686] = 3,
    ACTIONS(229), 1,
      sym_identifier,
    ACTIONS(231), 1,
      anon_sym_mut,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1697] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(233), 2,
      anon_sym_const,
      anon_sym_mut,
  [1706] = 3,
    ACTIONS(217), 1,
      sym_identifier,
    ACTIONS(235), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1717] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(181), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1726] = 3,
    ACTIONS(129), 1,
      sym_identifier,
    STATE(93), 1,
      sym_parameter,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1737] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(200), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1746] = 3,
    ACTIONS(237), 1,
      anon_sym_LBRACE,
    STATE(54), 1,
      sym_function_body,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1757] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(239), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1766] = 3,
    ACTIONS(217), 1,
      sym_identifier,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1777] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(207), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1786] = 2,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1794] = 2,
    ACTIONS(245), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1802] = 2,
    ACTIONS(247), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1810] = 2,
    ACTIONS(249), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1818] = 2,
    ACTIONS(251), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1826] = 2,
    ACTIONS(253), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1834] = 2,
    ACTIONS(255), 1,
      anon_sym_DASH_GT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1842] = 2,
    ACTIONS(257), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1850] = 2,
    ACTIONS(259), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1858] = 2,
    ACTIONS(261), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1866] = 2,
    ACTIONS(263), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1874] = 2,
    ACTIONS(265), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1882] = 2,
    ACTIONS(267), 1,
      anon_sym_DASH_GT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1890] = 2,
    ACTIONS(269), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1898] = 2,
    ACTIONS(271), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1906] = 2,
    ACTIONS(273), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1914] = 2,
    ACTIONS(275), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1922] = 2,
    ACTIONS(277), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1930] = 2,
    ACTIONS(279), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1938] = 2,
    ACTIONS(281), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1946] = 2,
    ACTIONS(283), 1,
      sym_int,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1954] = 2,
    ACTIONS(285), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1962] = 2,
    ACTIONS(287), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1970] = 2,
    ACTIONS(289), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1978] = 2,
    ACTIONS(291), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1986] = 2,
    ACTIONS(293), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1994] = 2,
    ACTIONS(295), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2002] = 2,
    ACTIONS(297), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2010] = 2,
    ACTIONS(299), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2018] = 2,
    ACTIONS(217), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2026] = 2,
    ACTIONS(301), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2034] = 2,
    ACTIONS(303), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2042] = 2,
    ACTIONS(305), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2050] = 2,
    ACTIONS(307), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2058] = 2,
    ACTIONS(309), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2066] = 2,
    ACTIONS(311), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2074] = 2,
    ACTIONS(313), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2082] = 2,
    ACTIONS(315), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2090] = 2,
    ACTIONS(317), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 50,
  [SMALL_STATE(4)] = 97,
  [SMALL_STATE(5)] = 144,
  [SMALL_STATE(6)] = 191,
  [SMALL_STATE(7)] = 238,
  [SMALL_STATE(8)] = 285,
  [SMALL_STATE(9)] = 332,
  [SMALL_STATE(10)] = 373,
  [SMALL_STATE(11)] = 411,
  [SMALL_STATE(12)] = 449,
  [SMALL_STATE(13)] = 484,
  [SMALL_STATE(14)] = 519,
  [SMALL_STATE(15)] = 554,
  [SMALL_STATE(16)] = 589,
  [SMALL_STATE(17)] = 624,
  [SMALL_STATE(18)] = 659,
  [SMALL_STATE(19)] = 697,
  [SMALL_STATE(20)] = 735,
  [SMALL_STATE(21)] = 772,
  [SMALL_STATE(22)] = 809,
  [SMALL_STATE(23)] = 846,
  [SMALL_STATE(24)] = 883,
  [SMALL_STATE(25)] = 920,
  [SMALL_STATE(26)] = 943,
  [SMALL_STATE(27)] = 963,
  [SMALL_STATE(28)] = 983,
  [SMALL_STATE(29)] = 1001,
  [SMALL_STATE(30)] = 1013,
  [SMALL_STATE(31)] = 1025,
  [SMALL_STATE(32)] = 1038,
  [SMALL_STATE(33)] = 1049,
  [SMALL_STATE(34)] = 1062,
  [SMALL_STATE(35)] = 1073,
  [SMALL_STATE(36)] = 1086,
  [SMALL_STATE(37)] = 1097,
  [SMALL_STATE(38)] = 1110,
  [SMALL_STATE(39)] = 1123,
  [SMALL_STATE(40)] = 1134,
  [SMALL_STATE(41)] = 1145,
  [SMALL_STATE(42)] = 1158,
  [SMALL_STATE(43)] = 1175,
  [SMALL_STATE(44)] = 1186,
  [SMALL_STATE(45)] = 1199,
  [SMALL_STATE(46)] = 1212,
  [SMALL_STATE(47)] = 1223,
  [SMALL_STATE(48)] = 1234,
  [SMALL_STATE(49)] = 1245,
  [SMALL_STATE(50)] = 1256,
  [SMALL_STATE(51)] = 1267,
  [SMALL_STATE(52)] = 1278,
  [SMALL_STATE(53)] = 1291,
  [SMALL_STATE(54)] = 1304,
  [SMALL_STATE(55)] = 1317,
  [SMALL_STATE(56)] = 1330,
  [SMALL_STATE(57)] = 1343,
  [SMALL_STATE(58)] = 1356,
  [SMALL_STATE(59)] = 1369,
  [SMALL_STATE(60)] = 1382,
  [SMALL_STATE(61)] = 1395,
  [SMALL_STATE(62)] = 1406,
  [SMALL_STATE(63)] = 1417,
  [SMALL_STATE(64)] = 1428,
  [SMALL_STATE(65)] = 1441,
  [SMALL_STATE(66)] = 1452,
  [SMALL_STATE(67)] = 1465,
  [SMALL_STATE(68)] = 1479,
  [SMALL_STATE(69)] = 1493,
  [SMALL_STATE(70)] = 1507,
  [SMALL_STATE(71)] = 1521,
  [SMALL_STATE(72)] = 1535,
  [SMALL_STATE(73)] = 1549,
  [SMALL_STATE(74)] = 1563,
  [SMALL_STATE(75)] = 1577,
  [SMALL_STATE(76)] = 1591,
  [SMALL_STATE(77)] = 1605,
  [SMALL_STATE(78)] = 1619,
  [SMALL_STATE(79)] = 1633,
  [SMALL_STATE(80)] = 1644,
  [SMALL_STATE(81)] = 1655,
  [SMALL_STATE(82)] = 1666,
  [SMALL_STATE(83)] = 1677,
  [SMALL_STATE(84)] = 1686,
  [SMALL_STATE(85)] = 1697,
  [SMALL_STATE(86)] = 1706,
  [SMALL_STATE(87)] = 1717,
  [SMALL_STATE(88)] = 1726,
  [SMALL_STATE(89)] = 1737,
  [SMALL_STATE(90)] = 1746,
  [SMALL_STATE(91)] = 1757,
  [SMALL_STATE(92)] = 1766,
  [SMALL_STATE(93)] = 1777,
  [SMALL_STATE(94)] = 1786,
  [SMALL_STATE(95)] = 1794,
  [SMALL_STATE(96)] = 1802,
  [SMALL_STATE(97)] = 1810,
  [SMALL_STATE(98)] = 1818,
  [SMALL_STATE(99)] = 1826,
  [SMALL_STATE(100)] = 1834,
  [SMALL_STATE(101)] = 1842,
  [SMALL_STATE(102)] = 1850,
  [SMALL_STATE(103)] = 1858,
  [SMALL_STATE(104)] = 1866,
  [SMALL_STATE(105)] = 1874,
  [SMALL_STATE(106)] = 1882,
  [SMALL_STATE(107)] = 1890,
  [SMALL_STATE(108)] = 1898,
  [SMALL_STATE(109)] = 1906,
  [SMALL_STATE(110)] = 1914,
  [SMALL_STATE(111)] = 1922,
  [SMALL_STATE(112)] = 1930,
  [SMALL_STATE(113)] = 1938,
  [SMALL_STATE(114)] = 1946,
  [SMALL_STATE(115)] = 1954,
  [SMALL_STATE(116)] = 1962,
  [SMALL_STATE(117)] = 1970,
  [SMALL_STATE(118)] = 1978,
  [SMALL_STATE(119)] = 1986,
  [SMALL_STATE(120)] = 1994,
  [SMALL_STATE(121)] = 2002,
  [SMALL_STATE(122)] = 2010,
  [SMALL_STATE(123)] = 2018,
  [SMALL_STATE(124)] = 2026,
  [SMALL_STATE(125)] = 2034,
  [SMALL_STATE(126)] = 2042,
  [SMALL_STATE(127)] = 2050,
  [SMALL_STATE(128)] = 2058,
  [SMALL_STATE(129)] = 2066,
  [SMALL_STATE(130)] = 2074,
  [SMALL_STATE(131)] = 2082,
  [SMALL_STATE(132)] = 2090,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_body_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_body_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_body_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_body_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lvalue, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_access, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_access, 4, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_body, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_body, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_statement, 4, 0, 1),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_statement, 4, 0, 1),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 5, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_expression, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 6, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 6, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pointer_type, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call_expression, 4, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_body, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_body, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pointer_type, 4, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 4, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call_expression, 5, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 5, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call_expression, 6, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 7, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 7, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_copy_expression, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 1, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_expression_repeat1, 2, 0, 0),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_returns_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_returns_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2, 0, 0),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2, 0, 0), SHIFT_REPEAT(112),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_returns, 3, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [259] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_returns, 4, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_returns, 1, 0, 0),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_header, 6, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_returns, 2, 0, 0),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_header, 7, 0, 0),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mir(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
